### ISSUE TITLE
Invalid password error massage

### ISSUE THREAD

**Issue by omerule** [chrisDeFouRire/sslping-cli#2] opened 2018-09-05 19:41 UTC
Good evening,
I'am really enjoying the sslping service thanks for making it.
I have since a few days a problem I can't fix with the sslping-cli.
If I log in to the website "https://sslping.com" with my credentials there is no problem.
When I use the same credential with sslping-cli I get the message:
Error: Invalid Password
    at /usr/lib/node_modules/sslping-cli/lib/index.js:35:10
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Is there something I can do to fix this error message?

Yours Kindly
Omer
The Netherlands

**Comment by chrisDeFouRire** [comment] 2018-09-23 00:31
Thanks for reporting this bug... It's fixed now, in version 1.0.7 ! you can type `npm install -g sslping-cli` to install the latest version.
(bug was caused by addition of google login, didn't retest the CLI). 

Thank you for your patience! Cheers

**Closed as completed by chrisDeFouRire** 2018-09-23 00:31 UTC
